### ISSUE TITLE
support multiple signalhubs

### ISSUE THREAD

**Issue by maxogden** [mafintosh/signalhub#1]
would be cool if you could do `signalhub([a, b, c, d])` and this handled using multiple simultaneous hubs

**Comment by maxogden** [comment]
i now run `https://signalhub.publicbits.org/`

**Comment by mafintosh** [comment]
4.0.0 now supports passing in an array of hub hosts

```
var hub = signalhub('my-app-name', [
  'https://hub1.example.com',
  'https://hub2.example.com'
])
```

**Comment by ngoldman** [comment]
:+1: kewl

**Comment by mafintosh** [comment]
Friends uses this now, https://github.com/moose-team/friends/commit/eb87d67deb518e12704b43678b28ed9f9aaa1bc7
