### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by NHQ** [mafintosh/signalhub#18]
I get this error running signal locally, and connecting to your public one.  It doesn't keep from working, but it can get to blowing up the console, especially if you connect to more than one hub.

**Comment by mafintosh** [comment]
this just an http connection timing out because its idle. we could send a heartbeat to avoid the extra logs

**Comment by NHQ** [comment]
What about closing the connection properly?  I think that would be preferably to a long-lived connection.

**Comment by mafintosh** [comment]
should be fixed in 4.4.0
