### ISSUE TITLE
Multiplexing streams?

### ISSUE THREAD

**Issue by bnolan** [mafintosh/signalhub#2]
How efficient is it following several hundred subscribers when using the client in the browser? Will it open n xmlhttprequests?

**Comment by maxogden** [comment]
it's 1 connection per channel. data is multiplexed for a channel. you only
listen for sub, you POST/PUT for pub

On Thursday, April 30, 2015, Ben Nolan <notifications@github.com> wrote:

> How efficient is it following several hundred subscribers when using the
> client in the browser? Will it open n xmlhttprequests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mafintosh/signalhub/issues/2>.
>


-- 
Sent from my phone

**Comment by bnolan** [comment]
Would the per-host connection limit be a problem here?

https://code.google.com/p/chromium/issues/detail?id=285567

**Comment by bnolan** [comment]
Made a pull request https://github.com/mafintosh/signalhub/pull/3 for subscribing to multiple streams.

**Comment by bnolan** [comment]
Pull request merged.

**Comment by bnolan** [comment]
You can now subscribe to an array of channels.
