### ISSUE TITLE
download dialogue opens

### ISSUE THREAD

**Issue by pguth** [mafintosh/signalhub#20]
Running signalhub behind a reverse proxy I am now dealing with the problem that, instead of displaying the page [like it should](https://signalhub.mafintosh.com/), the browsers download dialogue opens. 😟

I use the following `.htaccess`:

```sh
RewriteEngine On
RewriteBase /

RewriteCond %{ENV:HTTPS} !=on
RewriteRule ^(.*) https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

RewriteRule ^(.*) http://localhost:65300/$1 [P]
```

**Comment by pguth** [comment]
Adding the following line to the `.htaccess` solved the problem 😄:

```sh
Header set Content-Type text/plain
```

**Comment by mafintosh** [comment]
I dont think we set any headers actually for the status page. You wanna PR that?

**Comment by pguth** [comment]
You're right. Tested it and works 🚀: https://github.com/mafintosh/signalhub/pull/21
