### ISSUE TITLE
Example CLI interface not working?

### ISSUE THREAD

**Issue by CraigChilds94** [mafintosh/signalhub#6]
Hey there, I wanted to test this out because it looks really cool and easy to use. I thought I'd give the CLI examples a go but it doesn't appear to be doing anything.

I can listen on a port without errors being thrown but when I broadcast or subscribe it doesn't appear to be picked up. Nothing is being logged.

Maybe my version of Node doesn't like console.log? It's `v0.10.29`

It'd be great if you could help me out or let me know where I might be going wrong?

**Comment by CraigChilds94** [comment]
Note: updating to `v0.12.2` didn't appear to do anything.

**Comment by CraigChilds94** [comment]
It appears as though getting a response is pretty slow?

**Comment by mafintosh** [comment]
Sorry. I missed this issue. Can you share the cli commands you are running?

**Comment by CraigChilds94** [comment]
I'm running the ones which were specified in your README

**Comment by diffalot** [comment]
I'm running into this too.  After a fresh checkout from master and a clean `npm install` I run:

    ./bin.js listen -p 8080

and then in another terminal I run 

    ./bin.js broadcast test channel '{"test":"hello"}' -p 8080 -h localhost

and nothing echoes in the listening terminal (looking at ./bin.js it seems like something should)

**Comment by mafintosh** [comment]
Should be fixed in the latest version by @diffalot
